[package]
  cjc-version = "0.53.18"
  compile-option = "--dy-std --dy-libs -O2"
  description = "Columns game"
  link-option = ""
  name = "Columns"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.2.2"
  package-configuration = {}

[dependencies]
  cjsfml = { path = "dependencies/cjsfml" }
  customiterators = { path = "dependencies/customiterators" }
  dgengine = { path = "dependencies/dgengine" }
